// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odiivnogvuqqzxzzexfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kaWl2bm9ndnVxcXp4enpleGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODgzODEsImV4cCI6MjA2NTA2NDM4MX0.gcifS7BCMiXPmytLFrzQuo9al5eiwUfdm9nX6UglEoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);